services:
  replibyte:
    build: .
    container_name: replibyte
    image: registry.viaero.net/replibyte:v0.2 # bump this version after updating
    environment:
      - "S3_BUCKET=$S3_BUCKET"
      - "S3_REGION=us-east-1"
      - "S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID"
      - "S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY"
      - "CONNECTION_URI=$CONNECTION_URI"
      - "LOCAL_CONNECTION_URL=$LOCAL_CONNECTION_URL"
      - "ENCRYPTION_SECRET=$ENCRYPTION_SECRET"
      - "S3_ENDPOINT=$S3_ENDPOINT"
    volumes:
      - $PWD/replibyte.yaml:/replibyte.yaml:ro
    command: "--config /replibyte.yaml dump create"
    stdin_open: true
    tty: true
    networks:
      - postgresql_net

networks:
  postgresql_net:
    external: true
    name: postgres_postgresql_net
